### ISSUE TITLE
Code Highlighting is Broken with Upgraded Packages

### ISSUE THREAD

**Issue by ghost** [jlengstorf/gatsby-intermediate#12]
If I checkout at the revision https://github.com/jlengstorf/gatsby-intermediate/commit/d14378259b2ccd303d17c563c3148fb26af26a76, run `yarn upgrade-interactive` and run `yarn workspace theme-dev develop` syntax highlighting breaks.

**Comment by jlengstorf** [comment]
@anindha are you getting any errors? any extra info you can provide about what "breaks" means in this context is super helpful for tracking down the cause

thanks!

**Comment by ghost** [comment]
@jlengstorf The code no longer has syntax highlighting but there is no error message in the console. Please let me know if I can help in anyway.

**Comment by mranthonysutton** [comment]
Getting the same issues. I've even tried removing:

`  if (!codeProps) {
    return <pre {...props} />;
  }
`

To see if maybe it was just not returning due to having no props, but still not receiving anything. The code loads, but no props for the theme or any of the styles within the code block.

**Comment by jlengstorf** [comment]
hey, y'all! thanks for your patience

I just ran the upgrade to duplicate and it still shows syntax highlighting for me

here's what I did:

1. cloned the repo
2. checked out `d143782`
3. ran `yarn upgrade-interactive` and selected all dependencies
4. ran `yarn outdated` and noticed that not all dependencies had upgraded
5. manually updated the remaining dependencies (see screenshots)
6. ran `yarn workspace theme-dev develop`

<img width="1755" alt="Screen Shot 2020-05-28 at 9 55 47 AM" src="https://user-images.githubusercontent.com/163561/83170529-8779d280-a0c9-11ea-9190-a294674ce7e7.png">
<img width="1755" alt="Screen Shot 2020-05-28 at 9 55 58 AM" src="https://user-images.githubusercontent.com/163561/83170532-89dc2c80-a0c9-11ea-99a4-e497a1b06bbb.png">

when I visit `http://localhost:8000` I still see syntax highlighting:

<img width="898" alt="Screen Shot 2020-05-28 at 9 57 28 AM" src="https://user-images.githubusercontent.com/163561/83170635-b55f1700-a0c9-11ea-8042-12989ced6ba0.png">


here's a screenshot of my terminal showing all deps up to date and only the packages updated

<img width="922" alt="Screen Shot 2020-05-28 at 9 58 37 AM" src="https://user-images.githubusercontent.com/163561/83170762-e0496b00-a0c9-11ea-90e7-4ef3f0d43558.png">


if you're still hitting this issue, can you please send over a repo to look at?

for now, I'm going to close since the deps appear to upgrade successfully
